### PR TITLE
Update gradles, dependencies, AndroidX, and deprecations

### PR DESCRIPTION
**Pull request by TacoTheDank**
Hello! Hope you don't mind rather large pull requests. I grouped them according to changes.

### 1st commit
- Update gradle wrapper to 6.5 using git bash
- (Also clean up duplicates in .gitignore.)

### 2nd commit
- Update Roboto font to 2.138 (from https://github.com/googlefonts/roboto/releases)

### 3rd commit
- Move version name and code from manifest to gradle
- Group support libraries from third-party ones

### 4th commit
- Reformat build.gradle, travis, and pmd rules to the .editorconfig

### 5th commit
- Update Android Studio 3.5.3 -> 4.0.0 ([changelog](https://developer.android.com/studio/releases))
- Update Jackson 2.10.0 -> 2.11.0 ([changelog](https://github.com/FasterXML/jackson/wiki))
- Update Commons Lang 3.9 -> 3.10 ([changelog](https://commons.apache.org/proper/commons-lang/release-history.html))
- Update Joda Time 2.10.5 -> 2.10.6 ([changelog](https://www.joda.org/joda-time/changes-report.html))
- Update OkHttp 3.12.8 -> 3.12.12 ([changelog](https://square.github.io/okhttp/changelog_3x/))
- Update buildTools 29.0.2 -> 29.0.3
- Update PMD 5.6.0 -> 5.8.1 ([changelog](https://github.com/pmd/pmd/releases?after=pmd_releases%2F6.6.0))

### 6th commit
- Migrate to AndroidX (adds on almost 0.5 MB to the APK for whatever reason, mostly bloat)
- On top of initial AndroidX versions:
  - Update AndroidX AppCompat 1.0.0 -> 1.1.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/appcompat))
  - Update AndroidX RecyclerView 1.0.0 -> 1.1.0 -> ([changelog](https://developer.android.com/jetpack/androidx/releases/recyclerview))
  - Update Google Material 1.0.0 -> 1.1.0 ([changelog](https://github.com/material-components/material-components-android/releases))

### 7th commit
- Leave out all of META-INF, it's all useless

### 8th commit
- Fix some deprecations (drops total number identified by lint from 51 to 6, yay!)

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks for the pull request! I've had a look through, and I'm happy with everything other than commit 7 (proguard + META-INF).

I'd like to hold off on enabling Proguard for now as the benefit is fairly small (RedReader's APK is already tiny compared to most apps), and there could be stability issues caused by attempts to use reflection to access deleted classes/methods/fields/annotations.

Also regarding META-INF, do you know what specifically is being removed and how much space this saves? Does it have any impact on app signing?

**Comment by QuantumBadger** [comment]
Also, just noticed there seem to be some useful-looking entries removed from `.gitignore`?

**Comment by QuantumBadger** [comment]
PMD seems to fail with the following error:

> Incremental analysis only supports PMD 6.0.0 and newer. Please upgrade from PMD 5.8.1 or disable incremental analysis.

I'm fine with just disabling incremental analysis for now, as newer versions of PMD currently fail with a huge number of errors.

**Comment by TacoTheDank** [comment]
@QuantumBadger 
>Also regarding META-INF, do you know what specifically is being removed and how much space this saves? Does it have any impact on app signing?

It's just stuff like loads of txts that list library versions being used, as well as license texts and things like that. It's not needed. It usually shaves off a few kilobytes from the APK. If you want, you can use [apktool](https://ibotpeaches.github.io/Apktool/) on your 1.10 build and take a look inside.

**Comment by TacoTheDank** [comment]
> I'm fine with just disabling incremental analysis for now, as newer versions of PMD currently fail with a huge number of errors.

I think this is probably because 6.0.0+ targets Java 1.9? ([this?](https://github.com/pmd/pmd/releases/tag/pmd_releases/6.0.0#java-9-support))

`
Java 9 support is enabled by default. You can switch back to an older java version
via the command line, e.g. -language java -version 1.8.
`

**Comment by TacoTheDank** [comment]
@QuantumBadger Also I'll leave the proguard file in case you ever want to use it in the future for anything.

**Comment by TacoTheDank** [comment]
@QuantumBadger Everything alright?

**Comment by QuantumBadger** [comment]
Yep, this looks good now, thanks! Sorry for the delay, I've been busy, and I had to fix PMD so this didn't break the build.

**Comment by QuantumBadger** [comment]
PMD fixes here: https://github.com/QuantumBadger/RedReader/commit/22c96d30778fdc1ece8216427b79ca4a7696c129

I also downgraded the version of the Android plugin, due to this known issue: https://youtrack.jetbrains.com/issue/IDEA-233929

**Comment by QuantumBadger** [comment]
Updated my Alpha generating script to look for the version details in `build.gradle`, and Alpha 201 successfully built.

Also re-authorised Travis CI, so that hopefully it adds notifications on PRs/commits when the build is broken.

**Comment by TacoTheDank** [comment]
Awesome, thanks!

**Comment by QuantumBadger** [comment]
Changelog updated here: https://github.com/QuantumBadger/RedReader/commit/f123595039591a7fa6c775bc0a95484dddddb362

**Pull request merged**
