### PR TITLE
Add custom header view for search post lists, fixes #496

### LINKED ISSUE #496: Search View instead of Dialog for Searching reddits
It will be great to add a Search View instead of the dialog to prompt user to enter the keyword in the Search functionality . It will help to create functionality like showing the suggestion on the basis of the of the old search also.

### PR DESCRIPTION
**Pull request by samdroid-apps**
Add a different header for search post lists.  This view allows for
the query and subreddit to be edited and searched again.

Screenshot (tablet):

image

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thank you! This generally looks fine to me, but the build is failing due to an unused import:

    /home/travis/build/QuantumBadger/RedReader/src/main/java/org/quantumbadger/redreader/adapters/RedditListingManager.java:25:	Avoid unused imports such as 'org.quantumbadger.redreader.views.PostListingHeader'

Would it be possible to fix this please before I merge?

**Comment by samdroid-apps** [comment]
Thanks for the review.  Rebased and fixed those issues.

**Comment by QuantumBadger** [comment]
Excellent, thanks! I'll merge this in.

**Comment by QuantumBadger** [comment]
I've put in a fix here for the keyboard being shown over the top of the search results, by preventing the EditText from immediately gaining focus:

https://github.com/QuantumBadger/RedReader/commit/52bd36e4933603c38c3e5b0203d019d2cd268b7f

**Comment by QuantumBadger** [comment]
Another fix here to prevent users from inserting newlines into the search fields :)

https://github.com/QuantumBadger/RedReader/commit/1d1499a3e3b58ad64ea61ee61c336288f91ef2b6

**Comment by QuantumBadger** [comment]
The search button wasn't getting greyed out when it was disabled, so I've modified it to always be clickable, even when the inputs haven't changed:

https://github.com/QuantumBadger/RedReader/commit/30bc1cd44836a48c416a29b4ea605409a7a84fe0

Also changed it so the button text is a translated string rather than hardcoded.

**Comment by QuantumBadger** [comment]
Finally, changelog updated here :)

https://github.com/QuantumBadger/RedReader/commit/b51a432e612c73bf0200538031bbc0861781e616

**Pull request merged**
