### PR TITLE
Register v.redd.it, /video, and /gallery links

### LINKED ISSUE #860: [Feauture Request] Register v.redd.it links to open in app
This would be a very nice addition due to the fact that most videos have a seperated audio/video stream

### PR DESCRIPTION
**Pull request by gavtroy**
Closes #860.

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thank you for submitting this, and sorry for the delayed review.

I've had a look through the code and am not sure I understand why the `PostCommentListingURL` needs to be modified to support videos -- we have support in the `LinkHandler` already for Reddit video links, using the `redditVideosPattern`. Do you know if there was a reason for this?

**Comment by gavtroy** [comment]
No worries and my own apologies as I will be out of contact for the next couple of weeks.

My memory is hazy but I believe that just opened the actual video, and there was no sidebar that would let us get to the comments. Treating it as a PostCommentListingURL, paired with the small change in LinkDispatchActivity, lets us open the discussion page instead. The links seem to work about the same as non-video posts except `redd.it/id` redirects to `reddit.com/comments/id` whereas `v.redd.it/id` annoyingly redirects to `reddit.com/video/id`.

**Comment by QuantumBadger** [comment]
@gavtroy Many thanks! I'll do some testing and get this merged soon.

**Comment by QuantumBadger** [comment]
Merged and changelog updated -- thanks again!

**Pull request merged**
