### PR TITLE
Adaptive icon

### PR DESCRIPTION
**Pull request by rileyinman**
Resolves my suggestion in #583 to add the existing icon as an adaptive one barring a new design. I converted the existing "R" logo into an SVG and used that as the icon foreground, with the background being a static color. I also moved the existing icons to `@mipmap` to follow Android convention. Let me know if you want me to make any changes!

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Hi @rileyinman, very sorry for the delayed response!

This looks good to me. Before I merge this in, please could you add copyright headers to the new XML files? Similar to the one at the top of here:

https://github.com/QuantumBadger/RedReader/blob/master/src/main/res/values/strings.xml

**Comment by rileyinman** [comment]
Of course! No worries about the delay, I know everyone has a life to live outside code 🙂

**Comment by QuantumBadger** [comment]
Thanks! I've merged this in now, and updated the changelog here: https://github.com/QuantumBadger/RedReader/commit/41c00205e4cbb1a34aa48cdaffedeffcd7855c4d

I'll also investigate if this has any implications for the alpha (which uses its own icon).

**Comment by QuantumBadger** [comment]
Icon added for the alpha here: https://github.com/QuantumBadger/RedReader/commit/b64f4d54a0c199425e2fabb0893c19924dc9732f

**Pull request merged**
