### PR TITLE
Issue#637: Implement copy to clip body of post

### PR DESCRIPTION
**Pull request by MichalFerencsik**
Issue: #637 Allow copy text from a post main body.

Description: Implement copy of post body to clipboard using OnLongClickListener in _CommentListing_
activity.

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks!

Normally when long-clicking in RedReader you'd expect the long-click context menu to appear. I think it might be better to (1) show the context menu when long-clicking (which is what already happens if you long-click the post title, above the post body), and (2) add an item to the context menu called "Copy self-text". This would be more in line with what people expect.

Let me know what you think :)

**Comment by MichalFerencsik** [comment]
Hi @QuantumBadger, 

**(1) show the context menu when long-clicking (which is what already happens if you long-click the post title, above the post body)**
_Can we resolve this by opening same dialog when user makes a long click on post itself?_

 **(2) add an item to the context menu called "Copy self-text". This would be more in line with what people expect.**
_Done, yet it would require migration, and I'm not sure about manifest change_

**Comment by QuantumBadger** [comment]
Great work, thanks!

This basically looks ready to merge, although I think there's a minor bug -- both "Copy" and "Copy Self-Text" seem to copy the self text? The first one used to copy the URL:

https://github.com/QuantumBadger/RedReader/pull/682/files#diff-efdaf8c90823a78e85dc5c0bf0c4fcfcR471

>  Can we resolve this by opening same dialog when user makes a long click on post itself?

Yes I think that's the right approach.

>  Done, yet it would require migration, and I'm not sure about manifest change

Your change looks fine to me, if you have any questions please let me know :)

**Comment by MichalFerencsik** [comment]
I reverted minor bug inserted by copying code due to update of Clipmanager. 

Is it ok now? 

Thanks,
Michal

**Comment by MichalFerencsik** [comment]
Hi @QuantumBadger, 

have you had time to look at this?

Thanks,
Michal

**Comment by QuantumBadger** [comment]
Thanks @MichalFerencsik, it looks fine. Merging in now!

**Comment by QuantumBadger** [comment]
Changelog updated: https://github.com/QuantumBadger/RedReader/commit/c5d49e2491df51cb0dfebdf6de581fc2ffa0bdd7

**Comment by QuantumBadger** [comment]
Changelog updated: https://github.com/QuantumBadger/RedReader/commit/3c4ff6211237f91145e710a9c57b1eb2893a7722 (correct commit this time :))

**Pull request merged**
