### PR TITLE
Save v.redd.it videos as mp4 when downloading

### PR DESCRIPTION
**Pull request by sharkwouter**
I'm not sure if this is the best approach here, but this does fix https://github.com/QuantumBadger/RedReader/issues/639

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks, this looks good!

At the moment this just checks if the URL string contains the text "v.redd.it", but it might be better to save the result of `uriFromString()` on line 443, and call `getHost()` to get the hostname:

    final URI uri = uriFromString(url);
    ...
    if("v.redd.it".equals(uri.getHost()) {
    ...

If you'd like to make (and test) the above change please go ahead, or otherwise I can merge as-is.

**Comment by sharkwouter** [comment]
I've made the requested change. It works just as well so I've added it to this pull request.

**Comment by sharkwouter** [comment]
Okay, now it actually passed the pmd test. My bad.

**Comment by QuantumBadger** [comment]
Perfect, thanks! I'll get this merged in.

**Comment by QuantumBadger** [comment]
Changelog updated: https://github.com/QuantumBadger/RedReader/commit/f594cd4010ff7206c169e8f0d1c98b5a6f3a387a

**Pull request merged**
