### PR TITLE
Switch over to Gradle

### PR DESCRIPTION
**Pull request by mvdan**
I moved the `res` folder to where it's stored in android Gradle projects. I can redo the PR keeping it in the old location, but in the long run you want to move it there.

I just set up the project and added the exact same deps that maven had.

### CODE REVIEW

**Comment by mvdan** [comment]
@QuantumBadger this is ready to be merged - travis is working with the new system too.

**Comment by QuantumBadger** [comment]
Fantastic -- thank you!

**Comment by mvdan** [comment]
Whoops, I forgot about the README.md and BUILD.md. Could you update those?

**Comment by QuantumBadger** [comment]
> Whoops, I forgot about the README.md and BUILD.md. Could you update those?

Done.

**Pull request merged**
