### PR TITLE
Further refinements to accessibility actions

### LINKED ISSUE #964: Add TalkBack accessibility actions
RedReader should have [custom accessibility actions](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo.AccessibilityAction) to allow TalkBack users to quickly up/downvote posts, collapse threads, etc. similar to the assignable swipe gesture actions for sighted users. Ideally, the order of the actions would be customizable and users can choose which actions they'd like to have enabled, again similar to the already existing support for swipe gestures. The lack of an efficient, accessible Reddit client is one of the major things keeping me on iOS, so solving this would really mean a lot to me!

### PR DESCRIPTION
**Pull request by codeofdusk**
This PR:

* Adds additional accessibility actions when viewing a post.
* Adds accessibility actions for editing and deleting posts and comments.
* Hides actions that require authentication from anonymous users.
* Attempts to fix actions from the self text view, but this isn't working (did I connect it to the wrong view?).

Checkstyle is failing and I'm not sure why (the output is now apparently in HTML and, while a file is referenced in the log, I can't find it).

Follow-up of #1045. Re #964.

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks, I'll review this when it's ready!

I've been refactoring `RedditPreparedPost`, and those changes may have an effect on this PR. At the moment I think the only thing that needs to change is that `RedditPreparedPost.Action` is now moved to `RedditPostActions.Action`. If you have any questions please let me know.

**Comment by codeofdusk** [comment]
Thanks @QuantumBadger! A few quick things if you get to it:

* It looks like these actions work on the post header (good), but not in the bodies of self posts (bad). How can I fix this?
* What's the easiest way to implement an action to jump focus to the first l1 comment from the header/body? Will this have to be a custom function or is there an action that does this that I'm missing?
* What's with the `kt` files? They appear to be in a different syntax (functional Java hybrid thing???). I think I can intyuit what's going on. Do you intend to migrate the entire project to this new format or only certain portions?

**Comment by codeofdusk** [comment]
CC @QuantumBadger.

**Comment by QuantumBadger** [comment]
Thanks @codeofdusk, I'll review this soon. There are some minor style warnings in the CI but I'm happy to fix those up.

I got an email saying you'd left a comment with some questions, but that comment's disappeared -- did you figure everything out or was there anything you still wanted to ask?

**Comment by codeofdusk** [comment]
> I got an email saying you'd left a comment with some questions, but that comment's disappeared -- did you figure everything out or was there anything you still wanted to ask?

I either figured out the questions or moved them to the main PR description.

**Comment by QuantumBadger** [comment]
Thanks @codeofdusk!

> Attempts to fix actions from the self text view, but this isn't working (did I connect it to the wrong view?).

I fixed this by attaching the actions to a different view -- I'm not sure why it wasn't working before, but I tested it after the change and it works now.

**Comment by codeofdusk** [comment]
@QuantumBadger Do you intend to mention this PR in the alpha changelog as well or is it too minor? I see it wasn't updated and didn't know if that was an oversight.

**Comment by QuantumBadger** [comment]
Thanks, added to alpha changelog!

**Pull request merged**
