### PR TITLE
Spanish updated!

### PR DESCRIPTION
**Pull request by moshpirit**
Please, let me know when a new version is ready to be released in order to translate it.

Note: Reddit should be written in capital letters also in English, shouldn't it?

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thank you!

> Please, let me know when a new version is ready to be released in order to translate it.

Sorry, I'll try and remember in future!

> Note: Reddit should be written in capital letters also in English, shouldn't it?

According to reddit, it should always be lowercase:

https://www.reddit.com/about/alien/

**Comment by moshpirit** [comment]
Oh, OK thanks :)

**Comment by QuantumBadger** [comment]
Just to let you know I'm planning on releasing v1.9.1 tomorrow. There's only one new string that needs translating since v1.9.0 ("Gallery Swipe Length").

**Comment by moshpirit** [comment]
Great! thanks for the comment, I'm going to translate it :)

**Pull request merged**
