### PR TITLE
Suggested subreddits for "Custom Location" now separated by account

### LINKED ISSUE #446: Make subreddit autocompletion account-specific
Subreddits visited/subscribed on one account shouldn't appear in the autocompletion list of another account.

https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/reddit/RedditSubredditHistory.java

### PR DESCRIPTION
**Pull request by Clubfan22**
Should fix #446

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks! Looks good, although I have a couple of minor comments:

I think `RedditAccount.getCanonicalUsername()` should be used instead of `RedditAccount.username`, to ensure that the lookup is case insensitive. Or even better, `RedditAccount` could probably be used as the key to the `HashMap` instead of `String` :)

It looks like the checks for `!SUBREDDITS.get(username).isEmpty()` should be inverted (at the moment it seems to be adding the defaults if the list is *not* empty!)

In fact, those checks are already done inside `putDefaultSubreddits()`, so no need to duplicate them:

	public static synchronized void addSubreddit(final RedditAccount account, final String name) throws RedditSubreddit.InvalidSubredditNameException
	{
		putDefaultSubreddits(account);
		SUBREDDITS.get(account).add(General.asciiLowercase(RedditSubreddit.stripRPrefix(name)));
	}

Generally fine though -- I'll merge once the above is fixed :)

**Comment by QuantumBadger** [comment]
Actually it looks like there could be an infinite loop when calling `putDefaultSubreddits()` from `addSubreddit()`. Maybe better to replace line 45 `addSubreddit(username, subreddit)` with a call to `add(General.asciiLowercase(RedditSubreddit.stripRPrefix(name)))` on the `HashSet` directly.

**Comment by Clubfan22** [comment]
Thanks for pointing out the flaws, should be fixed now!

**Comment by QuantumBadger** [comment]
Thanks!

Travis is failing, but I think that's a Travis issue (failing to download a library). I'll go ahead and merge this in :)

**Pull request merged**
