### PR TITLE
Remove spaces from custom subreddit input

### PR DESCRIPTION
**Pull request by ishults**
I wanted to add the ability to input subreddits into the "Custom Subreddit" dialog without having to delete spaces (my keyboard autocompletes and auto-adds them).  I didn't realize this feature was already supported though!  So this is just a change to the display when the user is inputting the subreddit, to ignore spaces.

### CODE REVIEW

**Comment by philipwhiuk** [comment]
Spaces aren't allowed, but underscores are:

https://github.com/reddit/reddit/blob/862a7e0fc5142058a88044f9254a8ec5db977a77/r2/r2/models/subreddit.py#L112

**Comment by ishults** [comment]
@philipwhiuk Correct, my change only affects spaces.  I don't think we should auto-correct spaces to underscores, as then it doesn't really resolve the issue; it just replaces the character to delete.  If I type "ask reddit", I mean "askreddit", not "ask_reddit".  Plus the removal (rather than the replacement) of spaces is inline with the existing logic. 

Or am I missing something?

**Comment by philipwhiuk** [comment]
> Plus the removal (rather than the replacement) of spaces is inline with the existing logic.

What existing logic?

**Comment by ishults** [comment]
@philipwhiuk https://github.com/ishults/RedReader/blob/remove_spaces_custom_subreddit/src/main/java/org/quantumbadger/redreader/activities/MainActivity.java#L279

**Comment by philipwhiuk** [comment]
Oh so we're replacing them when we actually do the API call anyway? Then definitely I agree this should be merged.

**Comment by QuantumBadger** [comment]
Thanks!

**Pull request merged**
