### PR TITLE
Allow comments button to be hidden

### PR DESCRIPTION
**Pull request by Cguy7777**
Thought it might be nice to be able to hide the Comments button in post listings, for users who never or rarely look at the comments, or access them by flinging. This also adds the option to **View Comments** from the post context menu.

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks, this looks good!

I think it would be best not to have the new "View Comments" menu item enabled by default though, as the post context menu is already pretty cluttered :)

**Comment by Cguy7777** [comment]
Good point, most people probably won't access the comments that way. I've removed it as a default.

**Comment by QuantumBadger** [comment]
Thanks!

The new code style check is failing above because there are a few lines longer than 100 chars :) It says there are thousands of warnings, however I've just fixed all of these so you may need to merge from master again.

**Comment by QuantumBadger** [comment]
Btw it's possible to run the above checks locally before pushing using:

    ./gradlew pmd lint checkstyle

**Comment by Cguy7777** [comment]
Thanks, I've fixed it right up for you. :-)

**Comment by QuantumBadger** [comment]
Thank you! Merged, and changelog updated.

**Pull request merged**
