### PR TITLE
Hide visited posts option

### PR DESCRIPTION
**Pull request by asoback**
Added behavior preference to not load/display visited posts.

In reference to issue #558

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thank you, this looks good to me!

**Comment by QuantumBadger** [comment]
I've inverted the preference to make it clearer -- it's now "hide read" rather than "show read": https://github.com/QuantumBadger/RedReader/commit/2bf7cddbb5b11c5be1e21bff73e8c95a58c5a667

**Comment by QuantumBadger** [comment]
Changelog updated: https://github.com/QuantumBadger/RedReader/commit/d22fad36e9901c8b8227ce1f11618324f12fab9a

**Comment by Ty2357364** [comment]
This is awesome. However, it works for a while, but then it forgets which ones I've read. (I like to view top of all time; am I the only one? The best posts come back and I have to click thru them again.)
Is there a limit on the number of posts that can be remembered as read? I'm sure there is a limit on the number of read posts you can store; could you store an index to jump to instead, like, "on this subreddit, the top 400 posts of all time have been read."? I'd miss new top posts, but it would be a nice option.

**Comment by QuantumBadger** [comment]
@Ty2357364 Thanks! There's a setting for how long that info is kept under "Cache > Delete cached flags after".

**Comment by Ty2357364** [comment]
@QuantumBadger Thank you! (Now I just wish I could keep the data forever and import it if I get a new phone... But I don't think that's realistic.)

**Pull request merged**
