### PR TITLE
Implement toggles for thumbnails and previews on spoiler posts

### LINKED ISSUE #864: [FEATURE REQUEST] Add "Show spoiler previews" and "Show spoiler thumbnails" options
Hi,

As the title says, I was hoping to have the option to enable and disable showing of spoiler previews and thumbnails. This feature is already available for NSFW posts, so I don't think it would be too difficult to implement (I've only taken a cursory glance at the code and don't know Java very well, so I don't really know). These options would be found in the Images/Video section of the settings, like it's NSFW counterpart.

Thanks!

### PR DESCRIPTION
**Pull request by FintasticMan**
Closes #864

I don't have any experience writing Java, and haven't tested this. I couldn't tell whether `post.spoiler` was the correct way to tell if a post is a spoiler, so could someone verify that? The comment on line 845 of PostListingFragment.java should be removed once that is done.

### CODE REVIEW

**Comment by FintasticMan** [comment]
I've tested this using the debug build from the CI, and everything seems to work.
I've also removed the comment about `post.spoiler`, because it works.
closes #864

**Comment by QuantumBadger** [comment]
Thanks for this! I've had a quick look and it seems fine to me. When I get a free moment I'll take a closer look and get this merged in.

**Comment by FintasticMan** [comment]
Awesome, thank you!

**Comment by QuantumBadger** [comment]
Looks like this all works correctly -- I've merged it in, updated the changelog, and rearranged the strings in date order. Thanks again!

**Pull request merged**
