### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by equeim**

### CODE REVIEW

**Comment by equeim** [comment]
@QuantumBadger it seems that update to project configuration is needed to allow updated actions.

**Comment by QuantumBadger** [comment]
Thanks @equeim, I've updated the repo settings to allow newer versions of those actions. I've also removed the broken Cirrus CI stuff in `master`.

**Comment by equeim** [comment]
@QuantumBadger actions/setup-java also needs to be whitelisted.

**Comment by QuantumBadger** [comment]
> @QuantumBadger actions/setup-java also needs to be whitelisted.

Done!

**Comment by equeim** [comment]
Also moved dependency versions to version catalog

**Pull request merged**
