### PR TITLE
Random fixes

### PR DESCRIPTION
**Pull request by mvdan**
Here I am showing love again :)

This PR is large but most of it is automated removing of redundant types.

### CODE REVIEW

**Comment by mvdan** [comment]
To provide some background:

* Java 1.7 should make development easier and perhaps even bring in some speed
* Bumped the libraries, still compiles and seems to run fine

Why isn't Travis running?

**Comment by QuantumBadger** [comment]
Excellent, thanks!

Not sure why Travis hasn't kicked in -- I'll merge this in and see what happens :)

**Comment by QuantumBadger** [comment]
Looks like the build failed:

```
* What went wrong:
A problem occurred configuring root project 'RedReader'.
> failed to find Build Tools revision 23.0.2
```

According to this an extra flag is needed in travis.yml:

https://github.com/travis-ci/travis-ci/issues/5036

I'll add it now :)

**Comment by mvdan** [comment]
I was about to link the very same issue. I forgot about it, and travis not running didn't help.

**Comment by QuantumBadger** [comment]
All working now -- thanks again!

**Pull request merged**
