### PR TITLE
Don't auto-collapse your comments or user-profile comments

### LINKED ISSUE #314: Don't apply min. comment hiding when viewing comments on a user's profile
And probably shouldn't apply to the user's own comments, if they drop below the threshold.

### PR DESCRIPTION
**Pull request by Cguy7777**
This prevents comments from being automatically collapsed due to the **Minimum comment score** if

- The comment is by you (the current user), or
- You are viewing comments on a user profile

Closes #314.

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks! Just one minor issue, the username comparison should be case insensitive. It's probably best to do this using `StringUtils.asciiLowercase()` to avoid locale issues (I'd change the `currentUserName` param to `currentUserNameLowercase` to avoid converting it every time).

**Comment by Cguy7777** [comment]
No problem! I've switched it to use the canonical username (lowercase and trimmed).

**Comment by Cguy7777** [comment]
@QuantumBadger It looks like the unit tests failed because it couldn't download Gradle to run them. The last commit was quite minor, this is probably good.

**Comment by QuantumBadger** [comment]
Perfect, thanks! Changelog updated here: https://github.com/QuantumBadger/RedReader/commit/19db5f8530d5bb404a1d76f19bcf2cf0d5f2095a

**Pull request merged**
