### PR TITLE
Updated Spanish translations <!-- 2015-10-31 -->

### PR DESCRIPTION
**Pull request by moshpirit**

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks for doing this so quickly!

**Comment by moshpirit** [comment]
Thank you for improving this great app! I use it everyday so I'm really glad to help to this project :)

**Comment by QuantumBadger** [comment]
Just to let you know, I'll be releasing v1.9.2 soon, and there are some new strings :)

**Comment by moshpirit** [comment]
Great! I'll translate them later!! :D thanks

**Pull request merged**
