### PR TITLE
Scroll to top when collapsing self-posts

### PR DESCRIPTION
**Pull request by ajgoda90**
Scroll to position 0 when collapsing self-posts so that it doesn't drop the user in the middle of lower comments when the self-post is long.

### CODE REVIEW

**Comment by ajgoda90** [comment]
Closing and resubmitting. Included old commits.

**Comment by ajgoda90** [comment]
Nevermind, I guess it doesn't matter that much.

**Comment by QuantumBadger** [comment]
Thanks, I'll get this merged in!

**Comment by QuantumBadger** [comment]
Changelog updated: https://github.com/QuantumBadger/RedReader/commit/977a588d7202a86434a5df1656a9cf97daf12be4

**Pull request merged**
