### PR TITLE
Add accessibility "concise mode" to make navigation more efficient for experienced Redditors

### LINKED ISSUE #971: Accessibility: add a user setting for more concise labels
At the moment, accessibility labels in RedReader are quite verbose, making quick scrolling and navigation inefficient for advanced users. For instance, the text "age:" and "domain:" before the respective elements can often be inferred, and other meta information can easily be abbreviated without loss of context for experienced Redditors.

To mitigate this, add a preference, disabled by default, in accessibility settings called "use concise language when possible". For some accessibility values, maintain a `concise` variant. When building labels, if the user preference is activated and a `concise` variant for a given accessibility element exists, use it in place of the original. Otherwise, use the original string (in other words, not all accessibility items need `concise` variants).

The following `concise` values should be defined and used whenever the new setting is enabled in place of the regular versions:

``` xml
	<string name="accessibility_subtitle_flair_withperiod_concise">[%s].</string>
	<string name="accessibility_subtitle_nsfw_withperiod_concise">NSFW.</string>
	<string name="accessibility_subtitle_points_withperiod_concise" tools:ignore="PluralsCandidate">%d up.</string>
	<string name="accessibility_subtitle_author_withperiod_concise">u/%s.</string>
	<string name="accessibility_subtitle_subreddit_withperiod_concise">r/%s.</string>
	<string name="accessibility_subtitle_domain_withperiod_concise">%s.</string>
	<string name="accessibility_subtitle_selfpost_withperiod_concise">Self.</string>
	<string name="accessibility_subtitle_comment_collapsed_concise">Collapsed.</string>
	<string name="accessibility_subtitle_author_submitter_withperiod_concise">u/%s, OP.</string>
	<string name="accessibility_subtitle_author_moderator_withperiod_concise">u/%s, mod.</string>
	<string name="accessibility_subtitle_author_submitter_moderator_withperiod_concise">u/%s, OP and mod.</string>
	<string name="accessibility_subtitle_author_submitter_admin_withperiod_concise">u/%s, OP and admin.</string>
	<string name="accessibility_subtitle_controversiality_withperiod_concise">Controversial.</string>
	<string name="accessibility_subtitle_upvote_ratio_withperiod_concise" tools:ignore="PluralsCandidate">%d percent up.</string>
	<string name="accessibility_comment_indent_level_concise" tools:ignore="PluralsCandidate">l%d.</string>
```

### PR DESCRIPTION
**Pull request by codeofdusk**
This PR implements the "concise" mode. Closes #971.

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks, this looks good!

If it makes things easier, it's possible to run the CI locally using the following four Gradle targets: pmd, checkstyle, lint, and test.

**Comment by codeofdusk** [comment]
@QuantumBadger I'm really struggling to get this to pass checkstyle, particularly because some of the string names are quite lengthy!

Should we shorten the names or disable the linter for the relevant lines? or can you think of something else to do?

**Comment by codeofdusk** [comment]
Note that this PR will merge conflict with #976 due to them both adding new strings.

**Comment by QuantumBadger** [comment]
Thanks @codeofdusk, I'll take a closer look at this tonight and decide what to do with the line lengths. As you say it might be best to shorten the strings.

**Comment by codeofdusk** [comment]
Looks like CI is passing!

**Comment by QuantumBadger** [comment]
Merged -- thanks again! I'll update the changelog in a moment.

**Comment by codeofdusk** [comment]
@QuantumBadger Maybe a better changelog entry would read:

> Accessibility: Add option to "use concise language when possible" (disabled by default) for more efficient navigation (thanks to codeofdusk)

**Comment by QuantumBadger** [comment]
Agreed, I've updated the changelog.

**Comment by codeofdusk** [comment]
Great! Though you might want to change the "relative level" entry to say "enabled by default", or change concise mode's to "off by default" (just for consistant word usage across entries).

Also, might you have time at some point to look into #964? All of these changes are making RedReader far superior in accessibility to any other Android Reddit client!

**Comment by codeofdusk** [comment]
Oh, and I'm not sure if read posts are distinguished visually in any way? (it's not stated in the accessibility header, and I couldn't tell by a few quick `git grep`s). But don't want to open an issue/PR to add it to accessibility if it's not shown visually!

**Comment by QuantumBadger** [comment]
Thanks, when I get a moment I'll update the changelog and have a look at #964.

> Oh, and I'm not sure if read posts are distinguished visually in any way?

Yeah, currently read posts are shown in a different colour. Thank you for #977, I'll review it soon.

**Pull request merged**
