### PR TITLE
Update Spanish translations

### PR DESCRIPTION
**Pull request by moshpirit**
and

### CODE REVIEW

**Comment by moshpirit** [comment]
Sorry I couldn't do it before, my laptop charger was broken

**Comment by moshpirit** [comment]
Sorry I couldn't do it before, my laptop charger was broken

**Comment by QuantumBadger** [comment]
> Sorry I couldn't do it before, my laptop charger was broken

That's fine -- thanks for doing this!

**Comment by moshpirit** [comment]
It's a pleasure :)

**Comment by QuantumBadger** [comment]
Just to let you know there are some more strings to translate, if you have time :) I'm planning on releasing v1.9.5 within the next couple of weeks (as soon as I've fixed some bugs with the new comment swiping feature).

**Comment by moshpirit** [comment]
Missed the mail! Sorry I'll translate them ASAP (in a couple of hours)

**Pull request merged**
