### PR TITLE
Add material design icons, remove unused icons

### PR DESCRIPTION
**Pull request by mateoeh**
* Replaces the remaining Holo icons with material icons

* Removes `ic_action_search` (unused)

* Replaces `ic_action_thumb_up` and `ic_action_thumb_down` with `action_upvote` and `action_downvote`, respectively

* Changes 'open in built-in browser' icon from `ic_action_page` to `ic_action_globe`, and changes 'open in external browser' icon from `ic_action_globe` to new `ic_action_external`, seen here: ic_action_external_light

Sample of changes:

Holo | Material
---- | ----
comments-holo | comments-material
main-holo | main-material
toolbar-holo | toolbar-material

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks! I've got a couple of minor comments:

* For the comment link buttons, I think the old globe looked clearer than the new globe :)
* The upvote/downvote icons were chosen to be the same as the ones used on the main reddit site. The new thinner arrows look more visually appealing, but I think on balance I'd sooner they kept the same design as the main site.

Other than that, this looks good!

**Comment by mateoeh** [comment]
I respectfully disagree about the globe icon... I think having one lone Holo icon in the midst of all the other material icons would look pretty strange. Perhaps this icon would be a better fit?

ic_link_black_24dp

**Comment by QuantumBadger** [comment]
Thanks, yes I prefer that to the Material Design globe. Another alternative would be to use the "open in browser" icon, although that could potentially be misleading.

**Comment by mateoeh** [comment]
Should be all good now :)

**Comment by veyndan** [comment]
Changes look awesome, would be great to see them merged

**Comment by QuantumBadger** [comment]
Merged, thanks!

**Pull request merged**
