### PR TITLE
Random Subreddit

### PR DESCRIPTION
**Pull request by krisdb**
Wrote this for myself, not sure if you want to incorporate it.  I tried to resuse the existing json parser, but had a hard time following it, so wrote my own.

### CODE REVIEW

**Comment by mvdan** [comment]
Looks like you branched off before #229 was merged, so there are conflicts. Could you rebase on top of the current master?

**Comment by mvdan** [comment]
Reping @krisdb

**Comment by QuantumBadger** [comment]
Before this is merged in, it should ideally:

* Make use of the CacheManager and its JSON parser, rather than manually making an HTTP request. This means it'll always respect reddit's API limits, and will make the request through the oAuth API.
* Include an option to hide the "random" option from the main screen of the app (with the option hidden by default)
* Detect attempts to go to /r/random via links (and via the "custom subreddit" option), and handle them correctly

If nobody else volunteers, I'll probably make the above changes myself for v1.9.1.

**Comment by Zelpa** [comment]
so is this still on the radar of things to be fixed in the future?

**Comment by QuantumBadger** [comment]
Closing this PR request as the code has significantly diverged, and I think there are better approaches to fixing this.

**Pull request closed without merging**
