### PR TITLE
Add video playback controls

### PR DESCRIPTION
**Pull request by ahomphophone**
Implemented #387. I added a media controller to the video view. Looks like all the playback logic was already in MediaVideoView. I just needed to create and set the media controller. 

This also disables the ability to finish the activity when tapping the video because that is how the playback controls appear and hide. I'm not sure if this should be a preference but my instinct is to tap on the video to bring up playback controls and just pressing the back button to exit.

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks!

Before I merge this in, please could you make it a preference (off by default) so that people can keep the old behaviour if they want?

**Comment by ahomphophone** [comment]
Ok. Added preference.

**Comment by QuantumBadger** [comment]
Great, thank you!

Sorry to be a pain, but it looks like there's one more thing: the changes to `BasicGestureHandler` break the abstraction (by generating two events for the same tap).

It should be possible to move the `performClick()` call (which us currently inside `BasicGestureHandler`) to the `onSingleTap()` callback in `ImageViewActivity`, if you make the `videoView` a member. No changes should be necessary to `BasicGestureHandler`.

I promise I'll merge it in once that's fixed :stuck_out_tongue:

**Comment by ahomphophone** [comment]
Ok sorry! Done.

**Comment by QuantumBadger** [comment]
Thank you! Merging in now.

**Comment by QuantumBadger** [comment]
Changelog updated: https://github.com/QuantumBadger/RedReader/commit/ded5c57aab5f1a6f62d2b3a40f25788e9ae4a0eb

**Pull request merged**
