### PR TITLE
Renaming

### PR DESCRIPTION
**Pull request by kheidler**
Replaced occurences of "RedReader" with "Scroll", adjusted package/folder structure, using a different OAuth token now.

### CODE REVIEW

**Comment by kheidler** [comment]
sorry about this, I got my branches mixed up (meant to pull this into my own master, not yours... :sweat:)

**Comment by QuantumBadger** [comment]
Fair enough.

As a side note, there's no need to clone the entire app to add new features -- I regularly accept pull requests.

(Alternatively, if you're just trying to make a quick buck off everyone's hard work, please examine your conscience ;))

**Comment by kheidler** [comment]
The primary purpose of my fork was to get to know the reddit api better and see whats possible to achieve with it and what isn't - a matured app like this seemed like a better starting point than starting from scratch.

I will definitely do what you suggested once I feel confident enough about my contributions. 

(I'm not here to make any money, but to learn, my conscience is okay with that :wink:)

**Comment by QuantumBadger** [comment]
Sounds good -- let me know if you have any questions about the code :)

**Pull request closed without merging**
