### PR TITLE
Fix preload before opening in external app

### PR DESCRIPTION
**Pull request by m3sv**
Should work with most links.

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks!

Are you sure this works for imgur though? I think the imgur API erroneously returns the `image/gif` mimetype for gifv files, which might be GIFs but are usually videos. We don't know which until actually fetching the image.

**Comment by m3sv** [comment]
Indeed, it doesn't work. I'll look in to it.

**Comment by QuantumBadger** [comment]
Maybe the `mp4` field returned by the imgur API could be of use. If it's set, then the mimetype should be `video/mp4`.

**Comment by m3sv** [comment]
I already fixed the problem. Just need to commit.

**Comment by QuantumBadger** [comment]
Excellent work, thank you. I'll merge this in now.

**Comment by QuantumBadger** [comment]
Changelog updated: https://github.com/QuantumBadger/RedReader/commit/48d38c83ddd839dac86ce4195201768d5a16468d

**Comment by QuantumBadger** [comment]
Alpha 99 now up.

**Pull request merged**
