### PR TITLE
Show the subreddit of comments when viewing user comments or the inbox

### LINKED ISSUE #363: [feature request] Show the subreddit (preferably in a different color) of a users posts/comments

### PR DESCRIPTION
**Pull request by Cguy7777**
This adds comments' subreddits to their headers when viewing user comments or the inbox (and potentially other places, but never in a Post Comment Listing).
Closes #363.

### CODE REVIEW

**Comment by japanesephundroid** [comment]
Thanks for this 👍

**Comment by QuantumBadger** [comment]
Thanks @Cguy7777!

One minor comment on this is regarding the way we do the upgrades -- I'd like to move away from the old method where we compare the last version number to the current version number, as this is unreliable and e.g. doesn't work for alpha users.

I've added a new class called `FeatureFlagHandler`, which handles upgrades on a per-feature basis rather than depending on version numbers. Please could you put the upgrade logic inside `FeatureFlagHandler.handleUpgrade()`? I've put an example feature in there which you can replace with this one.

**Comment by Cguy7777** [comment]
@QuantumBadger I've moved the upgrade logic to the `FeatureFlagHandler` class as requested. If there's anything else you'd like to discuss with the PR, feel free to ask. :-)

**Comment by japanesephundroid** [comment]
Speaking about alpha updates, would it be possible @QuantumBadger to put new changes to the top of the changelog for every Alpha update?

Currently the only way to see what changed is to check the changes one by one and try to work our the new ones or check the commits page.

**Comment by QuantumBadger** [comment]
@Cguy7777 Great stuff, thanks! I've merged this in.

@japanesephundroid That's a good idea -- Alpha 254 uses a separate changelog which is organised by date.

**Comment by japanesephundroid** [comment]
> @Cguy7777 Great stuff, thanks! I've merged this in.
> 
> @japanesephundroid That's a good idea -- Alpha 254 uses a separate changelog which is organised by date.

Just tested the new Alpha, both new features work great 👍.

1 small nitpick on the changelog is including the Alpha number somewhere before or after the date, since it's the most visible part of each new build. It can help with troubleshooting I think.

**Comment by QuantumBadger** [comment]
@japanesephundroid Yep, can do: https://github.com/QuantumBadger/RedReader/commit/b5211df047cd06a0be0094ce44c3189674cd1495

**Comment by japanesephundroid** [comment]
> @japanesephundroid Yep, can do: https://github.com/QuantumBadger/RedReader/commit/b5211df047cd06a0be0094ce44c3189674cd1495

👍

**Pull request merged**
